### ISSUE TITLE
Need a more complete sample

### ISSUE THREAD

**Issue by n8fr8** [vanitasvitae/smack-omemo-signal#1]
I have everything built, and working (aka not crashing) with Smack on Android. However, I am not sure what to do beyond the snippets of code you provide in the readme. How do I setup my key, publish pre-keys, discover devices, import keys, etc? 

All in all though, amazing work, and we are so excited to be integrating it.

**Comment by vanitasvitae** [comment]
Hi!
Great to see someone actually using the code. I'm looking forward for some feedback :)
Your key gets automatically generated, if no existing key was found. Same goes for a bundle with prekeys etc. Those get automatically published to the server. No need to do it manually (let me know, if this is a good idea, or if you'd like to do it manually in order to get some control).

The OmemoService also listens for incoming device list updates and once you try to encrypt a message for a recipient, all the bundles of the contact and your own are fetched and sessions are built (given that you didn't have had a session already before).

I'm not sure what you mean by "import keys" though.

**Comment by vanitasvitae** [comment]
[Here](https://gist.github.com/vanitasvitae/d3a747de4f8327bd8580e3f2348ae01c) you can take a look at the test client I use in order to test my module. I hope that helps you :)

**Comment by n8fr8** [comment]
I meant fetch pre-keys. I thought perhaps that had to be manually done per contact. It is great to have this all automated. It will make adoption by others so much easier.

**Comment by vanitasvitae** [comment]
Great to hear. Please let me know, if you have any more questions or encounter any barriers. I highly appreciate any form of feedback :) Also feel free to contact me via XMPP. You can find my jid [here](https://vanitasvitae.github.io).

**Comment by n8fr8** [comment]
It is working now! Is there some way to query whether a certain JID is capable of Omemo? SInce we are interoperating with clients that still speak OTR only, we will need to know that.

**Comment by vanitasvitae** [comment]
You can use
```
OmemoManager.resourceSupportsOmemo(Jid jid);
```

**Comment by n8fr8** [comment]
Ah thanks... i was working off a build from Feb 20, so didn't have the recent improvements.

**Comment by n8fr8** [comment]
All is working well enough for day 1... i can send and receive between our Android client, and ChatSecure iOS.

**Comment by n8fr8** [comment]
THIS IS AWESOME WORK! :1st_place_medal:

**Comment by vanitasvitae** [comment]
Thank you so much :)

**Comment by vanitasvitae** [comment]
@n8fr8 you can find additional information here: https://github.com/vanitasvitae/smack-omemo/blob/4.2/documentation/omemo.md

**Comment by n8fr8** [comment]
Regarding this:

"t should be noted, that before you can encrypt a message for a device, you have to trust its identity. smack-omemo will throw an UndecidedOmemoIdentityException whenever you try to send a message to a device, which the user has not yet decided to trust or untrust. "

I think we are going for a TOFU model where we only notify the user they MUST verify once a key has changed or been added. Any thoughts on that?

**Comment by vanitasvitae** [comment]
I think thats a good idea. You can get the undecided identities from the UndecidedOmemoException.

Also I recommend you this article from @iNPUTmice about device trusting: https://gultsch.de/trust.html

**Comment by n8fr8** [comment]
We support QR code scanning and invite links shared through other secure channels as ways of bootstrapping and verifying trust, so very much inline with the Conversations approach. We just have to port this over from OTR to OMEMO now! :)

**Comment by vanitasvitae** [comment]
That's actually a bug in ChatSecure-iOS. ChatSecure should recognize the EME tag and hide the body in encrypted messages.

**Comment by vanitasvitae** [comment]
@n8fr8 I saw that you are using the SignalFileBasedOmemoStore to store key material. Are you aware, that you can also implement the methods defined in SignalOmemoStore in to store information in eg. an SQL database?

**Comment by n8fr8** [comment]
Yes, and plan to do so. We will store in our existing SQLCipher database.

This is really just to get some testing going by our dev team.

**Comment by vanitasvitae** [comment]
I'm happy about feedback in any form, bug reports etc :smile:
