### ISSUE TITLE
Small glitch in README

### ISSUE THREAD

**Issue by abika** [vanitasvitae/smack-omemo-signal#2]
> In the next step we need to checkout the 4.2 branch and create some links in the Smack repository
> 
> cd smack-omemo
> git checkout master
> ln -s ../smack-omemo-signal/smack-omemo-signal smack-omemo-signal

master -> 4.2
(4.2 is already the current branch when you do `git clone`)

**Comment by vanitasvitae** [comment]
Ah yes you're right. I changed that some days ago :)
